from typing import List
from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    query: str = Field(
        ...,
        min_length=1,
        description="Question to ask the RAG knowledge assistant",
        json_schema_extra={"example": "What did the Cell Reports Medicine study find?"},
    )


class DocumentSource(BaseModel):
    content: str = Field(..., description="Retrieved context passage used to ground the response")


class QueryResponse(BaseModel):
    query: str = Field(..., description="The original query")
    answer: str = Field(..., description="Fact-grounded answer generated by the LLM")
    sources: List[DocumentSource] = Field(
        default_factory=list,
        description="Source citations / text chunks retrieved from vector store",
    )
